[package]
name = "stock_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yahoo_finance_api = "1.2.2"
chrono = "0.4.19"
tokio-test = "0.4.2"